// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: user.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UserService_UserSignup_FullMethodName  = "/pbU.UserService/UserSignup"
	UserService_ListUsers_FullMethodName   = "/pbU.UserService/ListUsers"
	UserService_UploadUsers_FullMethodName = "/pbU.UserService/UploadUsers"
	UserService_Chat_FullMethodName        = "/pbU.UserService/Chat"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// Unary RPC
	UserSignup(ctx context.Context, in *UserCreate, opts ...grpc.CallOption) (*Response, error)
	// Server Streaming RPC
	ListUsers(ctx context.Context, in *FetchAll, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
	// Client Streaming RPC
	UploadUsers(ctx context.Context, opts ...grpc.CallOption) (UserService_UploadUsersClient, error)
	// Bidirectional RPC
	Chat(ctx context.Context, opts ...grpc.CallOption) (UserService_ChatClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserSignup(ctx context.Context, in *UserCreate, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, UserService_UserSignup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *FetchAll, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_ListUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*UserDetails, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*UserDetails, error) {
	m := new(UserDetails)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) UploadUsers(ctx context.Context, opts ...grpc.CallOption) (UserService_UploadUsersClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], UserService_UploadUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceUploadUsersClient{ClientStream: stream}
	return x, nil
}

type UserService_UploadUsersClient interface {
	Send(*UserCreate) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type userServiceUploadUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceUploadUsersClient) Send(m *UserCreate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceUploadUsersClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (UserService_ChatClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[2], UserService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceChatClient{ClientStream: stream}
	return x, nil
}

type UserService_ChatClient interface {
	Send(*Message) error
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type userServiceChatClient struct {
	grpc.ClientStream
}

func (x *userServiceChatClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceChatClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// Unary RPC
	UserSignup(context.Context, *UserCreate) (*Response, error)
	// Server Streaming RPC
	ListUsers(*FetchAll, UserService_ListUsersServer) error
	// Client Streaming RPC
	UploadUsers(UserService_UploadUsersServer) error
	// Bidirectional RPC
	Chat(UserService_ChatServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) UserSignup(context.Context, *UserCreate) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSignup not implemented")
}
func (UnimplementedUserServiceServer) ListUsers(*FetchAll, UserService_ListUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserServiceServer) UploadUsers(UserService_UploadUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadUsers not implemented")
}
func (UnimplementedUserServiceServer) Chat(UserService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_UserSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserSignup(ctx, req.(*UserCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchAll)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{ServerStream: stream})
}

type UserService_ListUsersServer interface {
	Send(*UserDetails) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *UserDetails) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_UploadUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).UploadUsers(&userServiceUploadUsersServer{ServerStream: stream})
}

type UserService_UploadUsersServer interface {
	SendAndClose(*Response) error
	Recv() (*UserCreate, error)
	grpc.ServerStream
}

type userServiceUploadUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceUploadUsersServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceUploadUsersServer) Recv() (*UserCreate, error) {
	m := new(UserCreate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).Chat(&userServiceChatServer{ServerStream: stream})
}

type UserService_ChatServer interface {
	Send(*MessageResponse) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type userServiceChatServer struct {
	grpc.ServerStream
}

func (x *userServiceChatServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceChatServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbU.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserSignup",
			Handler:    _UserService_UserSignup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadUsers",
			Handler:       _UserService_UploadUsers_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _UserService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "user.proto",
}
